"""
Django settings for FirstDjango project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from django.conf.global_settings import LOGIN_REDIRECT_URL, LOGIN_URL #로그인 주소관련 모듈 추가
from django.conf.global_settings import LOGOUT_REDIRECT_URL #로그아웃 주소관련 모듈 추가

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#사용자가 로그인이 필요한 뷰에 접근했을 때 로그인페이지로 이동할 수 있는 URL
LOGIN_URL = '/user/login'
#로그인을 성공한 후 접속할 URL 경로
LOGIN_REDIRECT_URL = '/polls/'
#로그아웃을 성공한 후 접속할 URL 경로
LOGOUT_REDIRECT_URL = '/polls/' # '/user/login/'

#http://localhost:8000/auth/complete/google-oauth2
#http://127.0.0.1:8000/auth/complete/google-oauth2
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '486832436151-u5gftop2ilf6cpmnso88f6tfa0bvdf5n.apps.googleusercontent.com' #클라이언트 ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'C1gQw0F4g3sani7DC_WQEPr3' #클라이언트 보안 비밀


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yv(+^at2_6yhwpvf01u=5m*-4--$0poqnvapon6xqwt17#g916'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = ( #소셜 로그인 인증에 관한 백엔드를 설정
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',    # 사이트의 사용자 테이블에 구글유저를 추가하기 위해서 추가
    
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',    # polls 어플리케이션 추가
    'user',
    'social_django',    #(다운받은)소셜로그인 패키지관련 어플리케이션 추가
    'blog',
    'disqus',           #(다운받은)django_disqus 모듈 추가
    'django.contrib.sites', #외부 사이트 접근 기능 추가
    'favorite',
]
DISQUS_WEBSITE_SHORTNAME = '0171deki'
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FirstDjango.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends', #OAuth 엔진 추가
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'FirstDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'ko'    #en-us

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

#127.0.0.1:8000/uploads
MEDIA_URL = '/uploads/' #웹서버가 이미지를 찾을 때 사용할 URL
#C:\test\src\image
MEDIA_ROOT = os.path.join(BASE_DIR,'uploads') #사용자가 업로드한 파일을 저장할 위치

